### ISSUE TITLE
浏览器转成pdf和jekyll-pdf生成的pdf有什么区别呢?

### ISSUE THREAD

**Issue by ender233** [wodeni/nimo-markdown-cv#4]
1. 浏览器转成pdf和jekyll-pdf生成的pdf有什么区别呢?
2. "Generating PDFs in one command" 怎么使用? 
我我理解，你给的默认例子index.md已经 有了如下配置，是不是打开本地http服务后，应该有pdf文件动态产生？
```
pdf: true
---
```

**Comment by wodeni** [comment]
1. 都是用print版本的css 没啥区别我记得
2. 是的，但是前提是你有`jekyll-pdf`这个gem package。即便我有`pdf: true`，在package不存在的情况下，也是不会有pdf文件生成的。

**Comment by ender233** [comment]
多谢，jekyll-pdf我是安装了的，不过jekyll serve拉起来之后没有pdf文件自动生成.
不过, 既然都是一样的我就不关注了. chrome里面print成pdf好了.
