### ISSUE TITLE
jekyll-pdf 依赖的 digrst 没有注册， bundle install 报错

### ISSUE THREAD

**Issue by brownchow** [wodeni/nimo-markdown-cv#5]
`Downloading jekyll-pdf-0.1.7 revealed dependencies not in the API or the lockfile (digest (~> 0)).
Either installing with `--full-index` or running `bundle update jekyll-pdf` should fix the problem.`

https://rubygems.org/gems/jekyll-pdf ， 查看 jekyll-pdf 的依赖项：
_RUNTIME 依赖关系 (4):
jekyll >= 2.0, ~> 3.1
pdfkit ~> 0.8
wkhtmltopdf-installer ~> 0.12
digest ~> 0_

其中  digest ~> 0 显示未注册

**Comment by wodeni** [comment]
Removed jekyll-pdf due to its lack of maintenance. Closing now.
