### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by vvzzxd3** [wodeni/nimo-markdown-cv#8]
想请教几点：
1.主标题如何居中的？
2.主标题下的信息是添加的小图标吗？如何实现的？
3.二级标题是怎么在后面添加分割线的？
4.三级标题是如何日期放在最右侧的？

**Comment by wodeni** [comment]
https://github.com/wodeni/nimo-markdown-cv/blob/master/media/cv-screen.css 这里的css基本上实现了1-4。 信息是icons，在这里可以看到源码：https://github.com/wodeni/nimo-markdown-cv/blob/master/_includes/cv-contact.html 。

我记得用的是[foundation icons](https://zurb.com/playground/foundation-icon-fonts-3)。

**Comment by vvzzxd3** [comment]
感谢！
